### ISSUE TITLE
Flare Address

### ISSUE THREAD

**Issue by Skepptix** [xrpscan/xrpscan.com#12]
I noticed today that when I bring up my account through Trezor > XRP Beta Wallet > See full transaction history that it no longer shows my account associated with a Flare address, is this something that you changed recently? I was kinda freaked out and thought it got disconnected for some reason.

**Comment by xrpscanner** [comment]
Hi @Skepptix, can you please share your account address so we can see what's wrong? If you'd like to share it privately, please send a screenshot and other details at support@xrpscan.com . Thank you!

**Comment by xrpscanner** [comment]
Update: This was happening due to a caching issue on our side. We've cleared the cache, so it should be fixed. Can you please verify if it works for you? If not, we'd be happy to dig deeper and fix it.

**Comment by Skepptix** [comment]
It works! I see it again. Thank you!
