### ISSUE TITLE
Add new metric for XRP burned

### ISSUE THREAD

**Issue by wojake** [xrpscan/xrpscan.com#16]
@xrpscanner 

Could xrpscan add a new metric to the metrics [page](https://xrpscan.com/metrics), named `XRP burned` that tracks the amount of XRP burned?
## How to achieve this
For every ledger, add all transactions' fees together and use that as the amount of XRP burned.

We can use this method to even compute past ledger's data but it would be a hassle to retrieve all past ledgers and their respective transaction, and then computing them all.

**Comment by xrpscanner** [comment]
Added this to the TODO list. Aggregated tx fees can easily be recorded going forward, but you're right - backfilling this data may be challenging and may put strain on the full-history service.

**Comment by wojake** [comment]
Implemented.
