### ISSUE TITLE
Add Xrplorer's forensics servcies

### ISSUE THREAD

**Issue by wojake** [xrpscan/xrpscan.com#17]
I believe adding Xrplorer's forensic services would greatly reduce the amount of scammed victims, it would increase the XRP Ledger's transparency.

When someone searches for an address (activated or not), refer to Xrplorer's forensic DB which contains a list of reported accounts that are conducting illegal activities such as scamming and hacking, to name a few.

Currently, the XRP Ledger Foundation is sponsoring the basic package which you can use to access their advisory lists which contains these said reported accounts, I believe scams should be diminished from the XRP Ledger ecosystem, we can start by implementing Xrplorer's forensic services to everyday used applications like yours 😄.

When an account is deleted/not activated, it normally showcases this:
![image](https://user-images.githubusercontent.com/87929946/146637746-6e6b5970-46db-4c86-98e8-8f1b1bf4be13.png)

If you implement this feature, I recommend doing something similar to this:

When an account is searched by a user, go through Xrplorer's lists, if the address is contained in the said list, showcase a bright red warning, like:
![image](https://user-images.githubusercontent.com/87929946/146637901-624a367b-9ba8-43bc-8e11-e1d135ab1b6c.png)
or something simpler:
![image](https://user-images.githubusercontent.com/87929946/146637939-5f3d25e1-9aa1-4802-8395-eb2318cb9dbc.png)

This will increase xrpscan's reputation in the XRP Ledger ecosystem, it will also keep the XRP Ledger ecosystem safer and transparent.

@xrpscanner 

Links:
- https://xrplorer.com/
- https://xrplorer.com/products/advisorylist

**Comment by xrpscanner** [comment]
Hi @wojake,

Thank you for submitting this detailed feature request. We did have an integration with Xrplorer Forensics at one point (~Feb 2020). However due to abuse and to protect their intellectual property, we had to remove this integration.

![xrps-xrpf](https://user-images.githubusercontent.com/44958361/149200994-663bb403-20aa-4e6e-941e-9d07182e6789.jpg)
