### ISSUE TITLE
[Bug] Amendments sorting is wrong

### ISSUE THREAD

**Issue by rothexD** [xrpscan/xrpscan.com#27]
# Summary
It appears that the sorting of Amendments is wrong. I think this has something to do with the fact that we went into double digits on the minor number. I think the latest Version and Amendments should move up to the top so that the sorting is the same as before.

# Steps to reproduce

1. Navigate to https://xrpscan.com/amendments
2. Scroll down until you find version 1.10.0 of accepted Amendments 

## Example Image
![image](https://github.com/xrpscan/xrpscan.com/assets/56934789/b3800f9a-5f0b-4c4b-94fb-c04cbc130c06)

_Revision 1.1_

**Comment by pkcs8** [comment]
Hi @rothexD, thank you for reporting this sorting issue. This is now fixed and deployed live. The versions are now sorted by their semver.

![semver](https://github.com/xrpscan/xrpscan.com/assets/110373364/78eff8eb-29cb-489f-b9a2-d4daedbf089e)
