### ISSUE TITLE
tx date is error in xrpscan.com

### ISSUE THREAD

**Issue by xiaolouDGB** [xrpscan/xrpscan.com#31]
i found the date in the tx data is error ,the tx hash is https://xrpscan.com/tx/D48679E493842959383B3E8113AC0380EDF399FEFA8BE9FD774AD9D1ADA35B53
https://xrpscan.com/tx/7C5376ADC92E931551BB240E4B1AD00D647E8E538491F8FB1FE3C68E4BF39BED
https://xrpscan.com/tx/D7949BA083380B68123C832BED5871935959EDCED4DD72F742A4B44015055D52
they all show that date is Jan 07, 1970, 02:08:50 PM UTC

**Comment by pkcs8** [comment]
Hey @xiaolouDGB! Thank you for reporting this issue. This is indeed a bug. We will take a look and deploy a fix soon.

**Comment by pkcs8** [comment]
This bug has been fixed and transactions with invalid dates should not be created. If you notice any such transactions again, please let me know.
