### ISSUE TITLE
Feature request: "does not contain" filter in Advanced Search

### ISSUE THREAD

**Issue by mvadari** [xrpscan/xrpscan.com#45]
There is already a "contains" filter, having a "does not contain" filter should also be super useful (for e.g. partial addresses).

**Comment by pkcs8** [comment]
![d](https://github.com/user-attachments/assets/c955b7dc-e66b-4d9f-8855-9ac7581fc010)

**Comment by pkcs8** [comment]
Added `does not contain` option to account and string fields. Please try and let me know!

**Comment by mvadari** [comment]
Works great, thanks!

For accounts, it would also be helpful to have "starts with" - I was just using "contain" and realized that some other accounts were showing up because the string I was searching for was in the middle of the account ID.

**Comment by pkcs8** [comment]
There's `begins with` that does the same. I agree with you, `starts/begins with` query is quite useful and I use it all the time.

**Comment by mvadari** [comment]
> There's `begins with` that does the same. I agree with you, `starts/begins with` query is quite useful and I use it all the time.

Ah, didn't see that, thanks!
