### ISSUE TITLE
[request] "Yeas" and "nays" instead of "voters" and "vetoers"

### ISSUE THREAD

**Issue by thejohnfreeman** [xrpscan/xrpscan.com#7]
(Fat fingered submitting this issue early.)

On an individual [amendment page](https://xrpscan.com/amendment/89308AF3B8B10B7192C4E613E1D2E4D9BA64B2EE2D5232402AE82A6A7220D953), how about labeling the groups "yeas" and "nays" in the style of a vote, instead of "voters" and "vetoers"? I think it's much better terminology. All validators are voters, but they might vote differently. None of these votes is a veto, which typically implies unilateral nullification of a passed resolution. Yeas and nays matches the terminology used in human elections and resolutions.

**Comment by thejohnfreeman** [comment]
This would include changing the name of the Voters column on the [Amendments page](https://xrpscan.com/amendments).

**Comment by xrpscanner** [comment]
Agree with _veto_ being a semantically incorrect term. Adding this change as a part of Amendment info page improvement task.

![vote](https://user-images.githubusercontent.com/44958361/81501588-dddbc880-92f6-11ea-9716-05d993640a1d.png)

**Comment by xrpscanner** [comment]
The updated [amendment page](https://xrpscan.com/amendment/00C1FC4A53E60AB02C864641002B3172F38677E29C26C5406685179B37E1EDAC) is now live.
